### ISSUE TITLE
why `->` before return type

### ISSUE THREAD

**Issue by mobop** [mun-lang/mun#137]
i don't understand the use of this symbol. 
it's totally unnecessary. 

proposal: remove `->` before return type

**Comment by baszalmstra** [comment]
Having a symbol at all is for consistency. We want a symbol to associate a type to a construct. We use `:` to ascribe a binding (`let x:int`: `x` is of type `int`) and `->` to denote a return type (`fn f(int) -> int` applying `f` to an `int` results in an `int`).

The `->` is used to distinguish the return type from the rest of the signature. We used to have `:` but we choose to revert to the same as Rust (partly because it was confusing for users coming from Rust).

There are a lot of languages that use `->` (Mathematics, Rust, Swift, C++, Python) and there are a lot of languages using `:` (Typescript, Scala, Perl), there is no silver bullet. Here is a more formal explanation, which I think is also the reason Rust is using the *return arrow*. There are basically two cases where the return arrow makes an appearance:

1. Function item declaration: `fn foo(x: int) -> int {}`
2. Assignment of a function to a variable with explicit type: `let x : fn(int) -> int = foo` (*not implemented yet*)

One might say the arrow is clearer in the case where a function type is specified. To me `let x : fn(T) -> U;` is easier to understand than `let x : fn(T) : U;` but you may disagree. 

All in all, I think its a matter of preference, we choose to use the return arrow.

**Comment by mobop** [comment]
@baszalmstra i am not asking to use `:` . i am proposing not having a symbol at all. like Go or Zig.
